apiVersion: v1
kind: Service

metadata:
  annotations:
    networking.gke.io/load-balancer-type: Unknows

  name: prometheus
  namespace: monitoring

spec:
  loadBalancerIP: 5.6.7.8
  sessionAffinity: ClientIP
  type: LoadBalancer
